services:
  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - "2376:2376"
    networks:
      jenkins:
        aliases:
          - docker

  jenkins-blueocean:
    build:
      context: ./custom_jenkins
      dockerfile: Dockerfile
    container_name: jenkins-blueocean
    restart: on-failure
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    volumes:
      - jenkins-data:/var/jenkins_home
      - jenkins-docker-certs:/certs/client:ro
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      jenkins:

  potato-detector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: papita
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    networks:
      - api_network
    ports:
      - "5000:5000"
    volumes:
      - ./:/app 


  nginx: 
    image: nginx:latest
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
    - potato-detector
    networks:
      - api_network
    ports:
    - "80:80"

networks:
  jenkins:
  api_network:

volumes:
  jenkins-docker-certs:
  jenkins-data:
