stages:
  training:
    cmd: python train.py
    deps:
    - data/raw_dataset
    - params.yaml
    - train.py
    - utils.py
    outs:
    - models/model.pt
    - training_results/train_metrics.csv
  test_model:
    cmd: python test.py
    deps:
    - potatoes.jpg
    - test.py
    - utils.py
    outs:
    - test_results/potatoes.jpg