stages:
  training:
    cmd: python train.py
    deps:
    - data/raw_dataset
    - params.yaml
    - train.py
    - utils.py
    outs:
    - models/model_new.pt
    metrics:
    - training_results/train_metrics.csv
  model_testing:
    cmd: python model_performance.py
    deps:
    - models/model_old.pt
    - models/model_new.pt
    outs:
    - models/model.pt
    