stages:
  training:
    cmd: python train.py
    deps:
    - data/raw_dataset
    - params.yaml
    - train.py
    - utils.py
    outs:
    - models/model_new.pt
    metrics:
    - training_results/train_metrics.csv
  model_testing:
    cmd: python model_performance.py
    deps:
    - models/model_old.pt
    - models/model_new.pt
    outs:
    - models/model.pt
  conversion_to_onnx:
    cmd: python to_onnx.py
    deps:
    - models/model.pt
    outs:
    - models/model.onnx
  test_model:
    cmd: python test.py
    deps:
    - models/model.onnx
    - potatoes.jpg
    - test.py
    - utils.py
    outs:
    - test_results/potatoes.jpg